name: "💡 Feature request"
description: Idea for an improvement
labels: [feature-request]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe your idea
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be helpful?
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Card search
        - Card scanner
        - Watchlists
        - Collection
        - Deck builder
        - Market & prices
        - Profile & settings
        - Other
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Screenshots / examples (optional)
    validations:
      required: false
